# Build and release the Terraform provider (terraform-provider-ipam) to GitHub Releases.
# Run: goreleaser release --clean
# Or push a tag (e.g. v0.1.0) to trigger the GitHub Action.

version: 2
project_name: terraform-provider-ipam

builds:
  - id: terraform-provider-ipam
    dir: terraform-provider-ipam
    main: .
    binary: terraform-provider-ipam_{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}

archives:
  - id: terraform-provider-ipam
    format: zip
    name_template: "terraform-provider-ipam_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - terraform-provider-ipam
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "terraform-provider-ipam_{{ .Version }}_SHA256SUMS"

snapshot:
  version_template: "{{ .IncPatch }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  # Uses current repo (set github.owner/repo to override)
  name_template: "v{{ .Version }}"
  draft: false
